### ISSUE TITLE
Alguien tiene que controlar antes de despacharlas que las URL recibidas sean válidas

### ISSUE THREAD

**Issue by GoogleCodeExporter** [codenautas/taller-simple#3]
```
para que no pidan por ejemplo agregar una entidad que no existe (o que no está 
permitidas)
```

Original issue reported on code.google.com by `RaquelZS...@gmail.com` on 2 Oct 2014 at 3:58

**Comment by emilioplatzer** [comment]
Hay que trabajar en esta idea para agregar un módulo de codenautas que resuelva este problema

**Comment by emilioplatzer** [comment]
Ya backend-plus hace los controles necesarios sobre las URL.
